# Generated by Django 3.2.7 on 2021-09-08 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myfiles',
            old_name='myfiles',
            new_name='file',
        ),
    ]
