# Generated by Django 3.2.7 on 2021-09-08 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_myfiles_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myfiles',
            name='filename',
        ),
    ]
